name: news_app_1 
description: A Flutter news application. 

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  url_launcher: ^6.3.1

flutter:
  assets:
    - assets/News-1.png
    - assets/news_placeholder.png

http: ^0.13.5 